(ns the-hero-hammer.questions_spec
  (:require [the-hero-hammer.questions :refer :all]))

(defmacro all-questions-lol []
  (questions-m
    ("mtype" "Match solo queue or ranked?"
           "Solo" "Ranked")
    ("ladder" "What is your ranking?"
              "Bronze" "Silver" "Gold" "Platinum"
              "Diamond" "Master" "Challenger")
    ("poking" "I got poked a lot" "yes" "no")
    ("poking-o" "I poked my opponent a lot" "yes" "no")
    ("sustain" "I could not sustain well" "yes" "no")
    ("sustain-o" "My opponent could not sustain me" "yes" "no")
    ("first-blood" "I got first blood" "yes" "no")
    ("cc" "I got a lot of cc (stuns/slows)" "yes" "no")
    ("gank" "I was ganked quite often" "yes" "no")
    ("last-hit" "I had trouble last hitting minions" "yes" "no")
    ))

(defn all-heroes-lol []
  [
  "Aatrox"
  "Ahri"
  "Akali"
  "Alistar"
  "Amumu"
  "Anivia"
  "Annie"
  "Ashe"
  "Azir"
  "Bard"
  "Blitzcrank"
  "Brand"
  "Braum"
  "Caitlyn"
  "Cassiopeia"
  "Cho'Gath"
  "Corki"
  "Darius"
  "Diana"
  "Dr. Mundo"
  "Draven"
  "Ekko"
  "Elise"
  "Evelynn"
  "Ezreal"
  "Fiddlesticks"
  "Fiora"
  "Fizz"
  "Galio"
  "Gangplank"
  "Garen"
  "Gnar"
  "Gragas"
  "Graves"
  "Hecarim"
  "Heimerdinger"
  "Illaoi"
  "Irelia"
  "Janna"
  "Jarvan IV"
  "Jax"
  "Jayce"
  "Jinx"
  "Kalista"
  "Karma"
  "Karthus"
  "Kassadin"
  "Katarina"
  "Kayle"
  "Kennen"
  "Kha'Zix"
  "Kindred"
  "Kog'Maw"
  "LeBlanc"
  "Lee Sin"
  "Leona"
  "Lissandra"
  "Lucian"
  "Lulu"
  "Lux"
  "Malphite"
  "Malzahar"
  "Maokai"
  "Master Yi"
  "Miss Fortune"
  "Mordekaiser"
  "Morgana"
  "Nami"
  "Nasus"
  "Nautilus"
  "Nidalee"
  "Nocturne"
  "Nunu"
  "Olaf"
  "Orianna"
  "Pantheon"
  "Poppy"
  "Quinn"
  "Rammus"
  "Rek'Sai"
  "Renekton"
  "Rengar"
  "Riven"
  "Rumble"
  "Ryze"
  "Sejuani"
  "Shaco"
  "Shen"
  "Shyvana"
  "Singed"
  "Sion"
  "Sivir"
  "Skarner"
  "Sona"
  "Soraka"
  "Swain"
  "Syndra"
  "Tahm Kench"
  "Talon"
  "Taric"
  "Teemo"
  "Thresh"
  "Tristana"
  "Trundle"
  "Tryndamere"
  "Twisted Fate"
  "Twitch"
  "Udyr"
  "Urgot"
  "Varus"
  "Vayne"
  "Veigar"
  "Vel'Koz"
  "Vi"
  "Viktor"
  "Vladimir"
  "Volibear"
  "Warwick"
  "Wukong"
  "Xerath"
  "Xin Zhao"
  "Yasuo"
  "Yorick"
  "Zac"
  "Zed"
  "Ziggs"
  "Zilean"
  "Zyra"
  ]
)
